name: Bug report
description: Help us improve jsrepo.
labels: ["bug"]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for helping us fix **jsrepo**!
    - type: textarea
      id: desc
      attributes:
          label: Describe the issue
          description: What is happening right now? What is supposed to happen?
      validations:
          required: true
    - type: markdown
      attributes:
          value: |
              Most of the time it will be difficult to reproduce your issue if we don't have access to the source registry. 
              Please provide a public repository from any supported provider that can be used to produce your issue.

              **For build issues**: 
              Provide a link to the source repository where the issue can be produced as well as any reproduction steps.

              **For install issues**:
              Using the public registry please reproduce your issue in our 
              [project template](https://stackblitz.com/github/ieedan/jsrepo/tree/main/examples/project) then provide a link to the instance as well as any reproduction steps.
    - type: input
      id: reproLink
      attributes:
          label: Reproduction Link
          description: "https://github.com/ieedan/std"
      validations:
          required: true
    - type: textarea
      id: reproSteps
      attributes:
          label: Steps to reproduce
          description: |
              Run:
              ```
              jsrepo add utils/test
              ```
      validations:
          required: true
    - type: checkboxes
      id: terms
      attributes:
          options:
              - label: I have checked other issues to see if my issue was already reported or addressed
                required: true
              - label: I am willing to file a pull request for this feature
                required: false
