name: 🆕 Feature request
description: Help us improve jsrepo.
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve **jsrepo**!
        
  - type: textarea
    id: desc
    attributes:
      label: Describe the feature
      description: What doesn't jsrepo do now? What should it do?
    validations:
      required: true
      
  - type: checkboxes
    id: terms
    attributes:
        label: Validations
        description: Please make sure you have checked all of the following.
        options:
            - label: I have checked other issues to see if my issue was already reported or addressed
              required: true