name: CI

on:
    pull_request:
        branches:
            - main

jobs:
    CI:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: pnpm install

            - name: Lint
              run: pnpm check

            - name: Lint
              run: pnpm test

            - name: Build
              run: pnpm build

            - name: Build Blocks
              run: pnpm blocks:build
