name: CI

on:
    pull_request:

jobs:
    CI:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install dependencies
              run: pnpm install

            - name: Check Types
              run: pnpm check:types

            - name: Lint
              run: pnpm check

            - name: Test
              run: pnpm test
